### ISSUE TITLE
Since you're using it with template strings, make it a tag function.

### ISSUE THREAD

**Issue by AriaFallah** [steelbrain/cool-trim#2]
If you follow instructions here, and make it a tag function

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_template_literals

You could do it without parenthesis:

``` javascript
import trim from 'cool-trim'

trim`
  Top
    Child
  Another Top
` ==== `Top
  Child
AnotherTop`; // true
```

**Comment by steelbrain** [comment]
Are there any particular benefits of using them?

**Comment by AriaFallah** [comment]
@steelbrain no parenthesis is the only benefit I know of. I figured it'd perhaps look cleaner.

**Comment by steelbrain** [comment]
@AriaFallah Thanks again!

**Comment by AriaFallah** [comment]
No problem! I was glad to see your new tagged template literals repo :smile:
